# experiment name
exp_name: "A_mms_AAAI_HuiMin_Unet"
exp_desc: "mms using Huimin_Unet"

batch_size: 32
num_epoch: 50
learning_rate: 0.0001
weight_decay: 0.01
warm_up_epochs: 10
num_workers: 12

model_name: ${exp_name}
test_vendor: "A"
domain_label: False
ratio: 0.02
fast_train: False
pretrain: True
pretrain_file: "/home/hyaoad/remote/semi_medical/journal_code/journal_semi_dg/pretrain_res/resnet50_v1c.pth"
restore: False
restore_from: ${exp_name}

# lr
scheduler: 'StepLR'
T_max: 50
min_lr: 1e-6

# for cps
cps_weight: 2
cps_rampup: True
consistency_rampup: 5

# for cutmix
cutmix_mask_prop_range: [0.25, 0.5]
cutmix_boxmask_n_boxes: 3
cutmix_boxmask_fixed_aspect_ratio: True
cutmix_boxmask_by_size: True
cutmix_boxmask_outside_bounds: True
cutmix_boxmask_no_invert: True

fourier_augment: True
fourier_mode: 'AS'

# for bn
bn_eps: 0.00001
bn_momentum: 0.1

# for hydra
hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}_${exp_name}